version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql-task-management
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-task-management
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my-project

  app:
    container_name: app-task-management
    image: node:20
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./src:/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db-task-management
    command: sh -c "npm install && npm run start"
    depends_on:
      - db
    networks:
      - my-project

networks:
  my-project:
    driver: bridge
